-- Add more broker data
INSERT INTO brokers (name, slug, description, regulation, min_deposit, max_leverage, spreads_from, platforms, account_types, instruments, payment_methods, demo_account, mobile_trading, founded_year, headquarters) VALUES
  (
    'OANDA',
    'oanda',
    'Trusted forex broker with advanced trading tools and educational resources',
    'FCA, ASIC, NFA, CFTC',
    0.00,
    '1:50',
    0.9,
    ARRAY['MetaTrader 4', 'OANDA Trade', 'TradingView'],
    ARRAY['Standard', 'Premium'],
    ARRAY['Forex', 'Indices', 'Commodities', 'Bonds'],
    ARRAY['Bank Transfer', 'Credit Card', 'PayPal', 'ACH'],
    TRUE,
    TRUE,
    1996,
    'New York, USA'
  ),
  (
    'IG Group',
    'ig-group',
    'Global multi-asset broker with 50+ years of trading experience',
    'FCA, ASIC, MAS, BaFin',
    250.00,
    '1:200',
    0.6,
    ARRAY['MetaTrader 4', 'IG Trading Platform', 'ProRealTime'],
    ARRAY['Standard', 'VIP'],
    ARRAY['Forex', 'Stocks', 'Indices', 'Commodities', 'Crypto', 'Options'],
    ARRAY['Bank Transfer', 'Credit Card', 'Debit Card', 'PayPal'],
    TRUE,
    TRUE,
    1974,
    'London, UK'
  ),
  (
    'Plus500',
    'plus500',
    'Popular CFD trading platform with competitive spreads and user-friendly interface',
    'FCA, CySEC, ASIC, MAS',
    100.00,
    '1:30',
    0.7,
    ARRAY['Plus500 WebTrader', 'Plus500 App'],
    ARRAY['Standard'],
    ARRAY['Forex', 'Stocks', 'Indices', 'Commodities', 'Crypto', 'ETFs', 'Options'],
    ARRAY['Credit Card', 'Debit Card', 'PayPal', 'Skrill', 'Bank Transfer'],
    TRUE,
    TRUE,
    2008,
    'Haifa, Israel'
  ),
  (
    'eToro',
    'etoro',
    'Social trading platform with copy trading and innovative investment features',
    'FCA, CySEC, ASIC',
    50.00,
    '1:30',
    1.0,
    ARRAY['eToro Platform', 'eToro Mobile App'],
    ARRAY['Retail', 'Professional'],
    ARRAY['Forex', 'Stocks', 'Crypto', 'Indices', 'Commodities', 'ETFs'],
    ARRAY['Credit Card', 'Debit Card', 'PayPal', 'Bank Transfer', 'Skrill', 'Neteller'],
    TRUE,
    TRUE,
    2007,
    'Tel Aviv, Israel'
  ),
  (
    'Interactive Brokers',
    'interactive-brokers',
    'Professional trading platform for active traders with access to global markets',
    'SEC, FINRA, FCA, IIROC',
    0.00,
    '1:50',
    0.1,
    ARRAY['Trader Workstation', 'IBKR Mobile', 'Client Portal'],
    ARRAY['Individual', 'Joint', 'IRA', 'Corporate'],
    ARRAY['Stocks', 'Options', 'Futures', 'Forex', 'Bonds', 'Funds', 'Crypto'],
    ARRAY['Bank Transfer', 'ACH', 'Wire Transfer', 'Check'],
    TRUE,
    TRUE,
    1978,
    'Greenwich, USA'
  ),
  (
    'Forex.com',
    'forex-com',
    'Leading US-based forex broker with competitive pricing and excellent execution',
    'NFA, CFTC, FCA, ASIC',
    100.00,
    '1:50',
    0.8,
    ARRAY['MetaTrader 4', 'MetaTrader 5', 'TradingView', 'FOREXTrader'],
    ARRAY['Standard', 'Commission', 'DMA'],
    ARRAY['Forex', 'Indices', 'Commodities', 'Crypto'],
    ARRAY['Bank Transfer', 'Credit Card', 'Debit Card', 'ACH'],
    TRUE,
    TRUE,
    1999,
    'New York, USA'
  ),
  (
    'Saxo Bank',
    'saxo-bank',
    'Premium multi-asset broker with institutional-grade technology',
    'DFSA, FCA, ASIC, MAS',
    10000.00,
    '1:200',
    0.4,
    ARRAY['SaxoTraderGO', 'SaxoTraderPRO'],
    ARRAY['Classic', 'Platinum', 'VIP'],
    ARRAY['Stocks', 'Forex', 'Options', 'Futures', 'Bonds', 'ETFs', 'CFDs'],
    ARRAY['Bank Transfer', 'Credit Card'],
    TRUE,
    TRUE,
    1992,
    'Copenhagen, Denmark'
  ),
  (
    'FP Markets',
    'fp-markets',
    'Australian broker offering tight spreads and fast execution speeds',
    'ASIC, CySEC',
    100.00,
    '1:500',
    0.0,
    ARRAY['MetaTrader 4', 'MetaTrader 5', 'cTrader', 'IRESS'],
    ARRAY['Standard', 'Raw'],
    ARRAY['Forex', 'Indices', 'Commodities', 'Crypto', 'Stocks', 'Bonds'],
    ARRAY['Bank Transfer', 'Credit Card', 'PayPal', 'Neteller', 'Skrill'],
    TRUE,
    TRUE,
    2005,
    'Sydney, Australia'
  )
ON CONFLICT (slug) DO NOTHING;
