export const mockEvents = [
  {
    id: '1',
    title: 'Federal Reserve Interest Rate Decision',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    impact: 'High',
    country: 'US',
    forecast: 5.50,
    actual: null,
    previous: 5.25,
    description: 'The Fed is expected to announce its interest rate decision'
  },
  {
    id: '2',
    title: 'Eurozone Inflation Rate',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    impact: 'High',
    country: 'EU',
    forecast: 2.40,
    actual: null,
    previous: 2.60,
    description: 'Monthly inflation data for the Eurozone'
  },
  {
    id: '3',
    title: 'UK Retail Sales',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    impact: 'Medium',
    country: 'GB',
    forecast: 0.5,
    actual: null,
    previous: 0.8,
    description: 'Retail sales figures'
  },
  {
    id: '4',
    title: 'Japan GDP',
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    impact: 'High',
    country: 'JP',
    forecast: 1.2,
    actual: null,
    previous: 0.9,
    description: 'Quarterly GDP growth data'
  },
];

export const mockAssets = [
  {
    id: '1',
    symbol: 'EURUSD',
    type: 'forex',
    name: 'Euro/US Dollar',
    lastPrice: 1.0850,
    change: 0.25,
    changeAmount: 0.0027,
    high24h: 1.0920,
    low24h: 1.0780,
    volume: 450000000,
  },
  {
    id: '2',
    symbol: 'GBPUSD',
    type: 'forex',
    name: 'British Pound/US Dollar',
    lastPrice: 1.2650,
    change: -0.15,
    changeAmount: -0.0019,
    high24h: 1.2750,
    low24h: 1.2600,
    volume: 320000000,
  },
  {
    id: '3',
    symbol: 'BTC',
    type: 'crypto',
    name: 'Bitcoin',
    lastPrice: 45230.50,
    change: 2.30,
    changeAmount: 1020.00,
    high24h: 46500,
    low24h: 44100,
    volume: 28500000000,
  },
  {
    id: '4',
    symbol: 'ETH',
    type: 'crypto',
    name: 'Ethereum',
    lastPrice: 2380.40,
    change: 1.80,
    changeAmount: 42.15,
    high24h: 2450,
    low24h: 2300,
    volume: 15200000000,
  },
  {
    id: '5',
    symbol: 'GOLD',
    type: 'commodity',
    name: 'Gold Spot',
    lastPrice: 1980.50,
    change: 0.85,
    changeAmount: 16.75,
    high24h: 2010,
    low24h: 1950,
    volume: 5000000,
  },
  {
    id: '6',
    symbol: 'SPX',
    type: 'index',
    name: 'S&P 500',
    lastPrice: 4750.25,
    change: 1.20,
    changeAmount: 56.50,
    high24h: 4800,
    low24h: 4700,
    volume: undefined,
  },
  {
    id: '7',
    symbol: 'DAX',
    type: 'index',
    name: 'DAX',
    lastPrice: 17850.30,
    change: 0.95,
    changeAmount: 170.25,
    high24h: 17950,
    low24h: 17700,
    volume: undefined,
  },
];

export const mockNews = [
  {
    id: '1',
    title: 'Federal Reserve Signals Pause on Rate Hikes',
    url: 'https://example.com/fed-pause',
    source: 'Reuters',
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    category: 'Forex',
    summary: 'Fed officials suggest a pause in interest rate increases amid cooling inflation',
    imageUrl: 'https://via.placeholder.com/400x300?text=Federal+Reserve',
  },
  {
    id: '2',
    title: 'Bitcoin Surges Past $45,000 Resistance',
    url: 'https://example.com/bitcoin-rally',
    source: 'CoinTelegraph',
    publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    category: 'Crypto',
    summary: 'Major cryptocurrency breaks through key technical level amid positive market sentiment',
    imageUrl: 'https://via.placeholder.com/400x300?text=Bitcoin',
  },
  {
    id: '3',
    title: 'Gold Prices Climb on Economic Uncertainty',
    url: 'https://example.com/gold-climb',
    source: 'Bloomberg',
    publishedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    category: 'Commodity',
    summary: 'Safe haven asset benefits from geopolitical tensions and market volatility',
    imageUrl: 'https://via.placeholder.com/400x300?text=Gold',
  },
  {
    id: '4',
    title: 'European Markets Rally on Dovish ECB Signals',
    url: 'https://example.com/ecb-signals',
    source: 'Financial Times',
    publishedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    category: 'Forex',
    summary: 'European indices surge as ECB hints at potential rate cuts in 2024',
    imageUrl: 'https://via.placeholder.com/400x300?text=Europe',
  },
];
